### ISSUE TITLE
Setup of RIV calculation according to Mayr et al.

### ISSUE THREAD

**Issue by AlexanderToifl** [AlexanderToifl/RIV#3]
Currently, biax_recoil.in contains a jump to vrc.in (jump vrc.in loop), this seems to be an error.

TODO:
Set up all parameters for physically reasonable simulation. In most recent commit I changed some of them for debug purposes.

Plot stress versus number of recoils (data in deformation.txt)

**Comment by chri3005** [comment]
Jump should be to biax_recoil.in.

**Comment by AlexanderToifl** [comment]
Yes this solves the problem.

Another issue: The temperature after the amorphization seems to be lower than the intended 300K. Additionally, the biaxial deformation lowers the temperature as well. So before adding the recoils there is thermostatting step necessary.
